import { FormEvent, useEffect, useMemo, useState } from 'react'
import { NavLink, Navigate, Route, Routes } from 'react-router-dom'
import { api } from './lib/api'
import type { ImportResult, Namespace, PoolEntry, Tag, User } from './types/api'

const menu = [['/', '概览'], ['/tags', '标签库'], ['/imports', '批次导入'], ['/pool', '候选池'], ['/review', '审核中心']] as const

export function App() {
  const [user, setUser] = useState<User | null>(null)
  const [loading, setLoading] = useState(true)
  useEffect(() => { if (!localStorage.getItem('tagmanager-token')) { setLoading(false); return }; api.me().then(setUser).catch(() => localStorage.removeItem('tagmanager-token')).finally(() => setLoading(false)) }, [])
  if (loading) return <div className="grid min-h-screen place-items-center text-slate-500">正在载入控制台…</div>
  if (!user) return <Login onLogin={setUser} />
  return <div className="min-h-screen bg-paper"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><p className="text-lg font-bold text-ink">Tag Manager</p><p className="text-xs text-slate-500">LLM 辅助的可审核标签库</p></div><div className="text-right text-sm"><p className="font-medium">{user.email}</p><button className="text-brand" onClick={() => { localStorage.removeItem('tagmanager-token'); setUser(null) }}>退出</button></div></div></header><div className="mx-auto grid max-w-7xl gap-6 px-5 py-6 md:grid-cols-[190px_1fr]"><nav className="flex gap-2 overflow-auto md:flex-col">{menu.map(([to,label]) => <NavLink key={to} to={to} end={to === '/'} className={({isActive}) => `rounded-lg px-3 py-2 text-sm font-medium ${isActive ? 'bg-brand text-white' : 'text-slate-600 hover:bg-white'}`}>{label}</NavLink>)}</nav><main><Routes><Route path="/" element={<Dashboard />} /><Route path="/tags" element={<TagsPage />} /><Route path="/imports" element={<ImportPage />} /><Route path="/pool" element={<PoolPage />} /><Route path="/review" element={<ReviewPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></main></div></div>
}

function Login({ onLogin }: { onLogin: (user: User) => void }) { const [email,setEmail]=useState('admin@example.com');const [password,setPassword]=useState('change-me-now');const [error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setError('');try{const result=await api.login(email,password);localStorage.setItem('tagmanager-token',result.token);onLogin(result.user)}catch(err){setError(err instanceof Error ? err.message : '登录失败')}} return <div className="grid min-h-screen place-items-center bg-slate-950 p-5"><form onSubmit={submit} className="w-full max-w-sm rounded-2xl bg-white p-7 shadow-2xl"><h1 className="text-2xl font-bold">标签管理库</h1><p className="mt-2 text-sm text-slate-500">使用管理员账号进入审核控制台。</p><label className="mt-6 block text-sm font-medium">邮箱<input className="mt-1 w-full rounded-lg border p-2" value={email} onChange={e=>setEmail(e.target.value)} /></label><label className="mt-4 block text-sm font-medium">密码<input type="password" className="mt-1 w-full rounded-lg border p-2" value={password} onChange={e=>setPassword(e.target.value)} /></label>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button className="mt-6 w-full rounded-lg bg-brand px-4 py-2 font-semibold text-white">登录</button></form></div> }

function useNamespaces(){const [items,setItems]=useState<Namespace[]>([]);const [error,setError]=useState('');useEffect(()=>{api.namespaces().then(x=>setItems(x.data)).catch(e=>setError(e.message))},[]);return{items,error}}
function NamespacePicker({value,onChange,namespaces}:{value:string;onChange:(value:string)=>void;namespaces:Namespace[]}){return <select className="rounded-lg border bg-white px-3 py-2" value={value} onChange={e=>onChange(e.target.value)}><option value="">选择标签域</option>{namespaces.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select>}
function Card({title,value,detail}:{title:string;value:string|number;detail:string}){return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></article>}
function Dashboard(){const {items:namespaces,error}=useNamespaces();return <section><div className="flex items-start justify-between"><div><h1 className="text-2xl font-bold">运营概览</h1><p className="mt-1 text-slate-500">管理标签命中、候选积压和人工审核。</p></div></div>{error?<Notice message={error}/>:<><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card title="标签域" value={namespaces.length} detail="按业务域隔离规则和候选阈值"/><Card title="发布标签" value="—" detail="选择域后可在标签库查看"/><Card title="候选池" value="—" detail="达到阈值后自动创建汇总任务"/><Card title="待审核" value="—" detail="模型建议必须由人工批准才发布"/></div><section className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white p-6"><h2 className="font-semibold">开始使用</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-slate-600"><li>创建一个标签域并设置候选池阈值。</li><li>导入首批标签，候选池任务会调用已配置的 OpenAI 兼容模型。</li><li>在审核中心接受或驳回模型生成的标签增量。</li></ol></section></>}</section>}
function TagsPage(){const {items:namespaces,error}=useNamespaces();const [namespaceId,setNamespaceId]=useState('');const [query,setQuery]=useState('');const [tags,setTags]=useState<Tag[]>([]);useEffect(()=>{if(namespaceId)api.tags(namespaceId,query).then(x=>setTags(x.data)).catch(()=>setTags([]))},[namespaceId,query]);return <section><h1 className="text-2xl font-bold">标签库</h1><div className="mt-5 flex flex-wrap gap-3"><NamespacePicker value={namespaceId} onChange={setNamespaceId} namespaces={namespaces}/><input className="rounded-lg border px-3 py-2" placeholder="搜索规范标签" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&<Notice message={error}/>}<div className="mt-5 overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">规范标签</th><th className="p-3">别名</th><th className="p-3">描述</th><th className="p-3">版本</th></tr></thead><tbody>{tags.map(tag=><tr key={tag.id} className="border-t"><td className="p-3 font-medium">{tag.canonicalName}</td><td className="p-3 text-slate-600">{tag.aliases.join('、') || '—'}</td><td className="p-3 text-slate-600">{tag.description || '—'}</td><td className="p-3">v{tag.version}</td></tr>)}{namespaceId&&tags.length===0&&<tr><td className="p-6 text-center text-slate-500" colSpan={4}>暂无已发布标签</td></tr>}</tbody></table></div></section>}
function ImportPage(){const {items:namespaces,error}=useNamespaces();const [namespaceId,setNamespaceId]=useState('');const [sourceName,setSourceName]=useState('');const [raw,setRaw]=useState('');const [initialSeed,setInitialSeed]=useState(false);const [result,setResult]=useState<ImportResult|null>(null);const [message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();setMessage('');setResult(null);const tags=raw.split(/\r?\n|,/).map(v=>v.trim()).filter(Boolean);try{setResult(await api.importTags({namespaceId,sourceName,tags,initialSeed}))}catch(err){setMessage(err instanceof Error?err.message:'导入失败')}}return <section><h1 className="text-2xl font-bold">批次导入</h1><p className="mt-1 text-slate-500">已命中的规范标签或别名不会新增；未命中项会累计到候选池。</p><form onSubmit={submit} className="mt-6 max-w-3xl rounded-xl border bg-white p-5"><div className="flex flex-wrap gap-3"><NamespacePicker value={namespaceId} onChange={setNamespaceId} namespaces={namespaces}/><input className="rounded-lg border px-3 py-2" placeholder="来源名称，例如 2026-Q3 产品数据" value={sourceName} onChange={e=>setSourceName(e.target.value)}/></div><label className="mt-4 flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={initialSeed} onChange={e=>setInitialSeed(e.target.checked)}/>这是首批基线标签：立即创建模型整理任务</label><textarea className="mt-4 min-h-60 w-full rounded-lg border p-3" placeholder="每行一个标签，也可用逗号分隔" value={raw} onChange={e=>setRaw(e.target.value)} />{(message||error)&&<Notice message={message||error}/>}<button disabled={!namespaceId||!raw.trim()} className="mt-4 rounded-lg bg-brand px-4 py-2 font-semibold text-white disabled:opacity-50">提交并处理</button></form>{result&&<div className="mt-5 grid gap-3 sm:grid-cols-4"><Card title="总计" value={result.totalCount} detail="原始输入"/><Card title="已命中" value={result.matchedCount} detail="未新增标签"/><Card title="进入候选池" value={result.pooledCount} detail="等待阈值触发"/><Card title="无效项" value={result.invalidCount} detail={result.jobId?'已创建汇总任务':'等待阈值'} /></div>}</section>}
function PoolPage(){const {items:namespaces}=useNamespaces();const [namespaceId,setNamespaceId]=useState('');const [items,setItems]=useState<PoolEntry[]>([]);const [threshold,setThreshold]=useState(0);useEffect(()=>{if(namespaceId)api.pool(namespaceId).then(x=>{setItems(x.data);setThreshold(x.threshold)})},[namespaceId]);const progress=useMemo(()=>threshold?Math.min(100,Math.round(items.length/threshold*100)):0,[items,threshold]);return <section><h1 className="text-2xl font-bold">候选池</h1><p className="mt-1 text-slate-500">达到阈值时冻结当前集合，模型只处理冻结快照，避免新数据扰动审核。</p><div className="mt-5"><NamespacePicker value={namespaceId} onChange={setNamespaceId} namespaces={namespaces}/></div>{namespaceId&&<><div className="mt-5 rounded-xl border bg-white p-5"><div className="flex justify-between text-sm"><span>本轮候选 {items.length} / 阈值 {threshold}</span><span className="font-semibold text-brand">{progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded bg-slate-100"><div className="h-full bg-brand" style={{width:`${progress}%`}}/></div></div><div className="mt-5 overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3">规范化值</th><th className="p-3">原始样本</th><th className="p-3">出现次数</th><th className="p-3">最近出现</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t"><td className="p-3 font-medium">{item.normalizedName}</td><td className="p-3">{item.rawSample}</td><td className="p-3">{item.occurrenceCount}</td><td className="p-3 text-slate-500">{new Date(item.lastSeenAt).toLocaleString()}</td></tr>)}</tbody></table></div></>}</section>}
function ReviewPage(){const [proposals,setProposals]=useState<import('./types/api').Proposal[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [comments,setComments]=useState<Record<string,string>>({});const reload=()=>{ void api.proposals().then(x=>setProposals(x.data)).catch(e=>setError(e.message)) };useEffect(()=>{reload()},[]);async function decide(id:string,approve:boolean,version:number){setBusy(id);setError('');try{await api.decideProposal(id,{approve,version,comments:comments[id]??'',tags:[]});reload()}catch(err){setError(err instanceof Error?err.message:'审核提交失败')}finally{setBusy('')}}return <section><h1 className="text-2xl font-bold">审核中心</h1><p className="mt-1 text-slate-500">模型建议只能在审核通过后写入标签库；驳回将携带反馈重新进入模型汇总。</p>{error&&<Notice message={error}/>}<div className="mt-6 space-y-5">{proposals.map(proposal=><article key={proposal.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">提案 {proposal.id.slice(0,8)}</p><p className="mt-1 text-sm text-slate-500">生成于 {new Date(proposal.createdAt).toLocaleString()} · 版本 {proposal.version}</p></div><span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-800">{proposal.status}</span></div><div className="mt-5 space-y-3">{proposal.tags.map(tag=><div key={tag.id} className="rounded-lg border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{tag.canonicalName}</p><p className="mt-1 text-sm text-slate-600">{tag.description}</p></div><span className="text-sm font-semibold text-brand">置信度 {Math.round(tag.confidence*100)}%</span></div><p className="mt-3 text-xs text-slate-500">别名：{tag.aliases.join('、')||'—'} · 覆盖 {tag.coveredEntryIds.length} 个候选输入</p><p className="mt-1 text-xs text-slate-500">理由：{tag.rationale||'—'}</p></div>)}</div><textarea className="mt-5 min-h-20 w-full rounded-lg border p-3 text-sm" placeholder="驳回时请填写模型修订反馈（可选）" value={comments[proposal.id]??''} onChange={e=>setComments({...comments,[proposal.id]:e.target.value})}/><div className="mt-3 flex gap-3"><button disabled={busy===proposal.id} onClick={()=>decide(proposal.id,true,proposal.version)} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">批准并发布</button><button disabled={busy===proposal.id} onClick={()=>decide(proposal.id,false,proposal.version)} className="rounded-lg border border-red-300 px-4 py-2 text-sm font-semibold text-red-700 disabled:opacity-50">驳回并再汇总</button></div></article>)}{proposals.length===0&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center"><p className="font-medium">暂无待审核提案</p><p className="mt-2 text-sm text-slate-500">候选池达到阈值、worker 成功调用模型后，提案会出现在这里。</p></div>}</div></section>}
function Notice({message}:{message:string}){return <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}
